# Pin npm packages by running ./bin/importmap

pin "application"
pin "@hotwired/turbo-rails", to: "turbo.min.js"
pin "@hotwired/stimulus", to: "stimulus.min.js"
pin "@hotwired/stimulus-loading", to: "stimulus-loading.js"
pin_all_from "app/javascript/controllers", under: "controllers"
pin "bpmn-js", to: "https://ga.jspm.io/npm:bpmn-js@17.11.1/index.js"
pin "bpmn-moddle", to: "https://ga.jspm.io/npm:bpmn-moddle@8.1.0/dist/index.esm.js"
pin "diagram-js", to: "https://ga.jspm.io/npm:diagram-js@14.11.3/lib/Diagram.js"
pin "diagram-js/lib/command/CommandInterceptor", to: "https://ga.jspm.io/npm:diagram-js@14.11.3/lib/command/CommandInterceptor.js"
pin "diagram-js/lib/draw/BaseRenderer", to: "https://ga.jspm.io/npm:diagram-js@14.11.3/lib/draw/BaseRenderer.js"
pin "diagram-js/lib/features/change-support", to: "https://ga.jspm.io/npm:diagram-js@14.11.3/lib/features/change-support/index.js"
pin "diagram-js/lib/features/outline", to: "https://ga.jspm.io/npm:diagram-js@14.11.3/lib/features/outline/index.js"
pin "diagram-js/lib/features/overlays", to: "https://ga.jspm.io/npm:diagram-js@14.11.3/lib/features/overlays/index.js"
pin "diagram-js/lib/features/root-elements", to: "https://ga.jspm.io/npm:diagram-js@14.11.3/lib/features/root-elements/index.js"
pin "diagram-js/lib/features/selection", to: "https://ga.jspm.io/npm:diagram-js@14.11.3/lib/features/selection/index.js"
pin "diagram-js/lib/i18n/translate", to: "https://ga.jspm.io/npm:diagram-js@14.11.3/lib/i18n/translate/index.js"
pin "diagram-js/lib/layout/LayoutUtil", to: "https://ga.jspm.io/npm:diagram-js@14.11.3/lib/layout/LayoutUtil.js"
pin "diagram-js/lib/util/EscapeUtil", to: "https://ga.jspm.io/npm:diagram-js@14.11.3/lib/util/EscapeUtil.js"
pin "diagram-js/lib/util/ModelUtil", to: "https://ga.jspm.io/npm:diagram-js@14.11.3/lib/util/ModelUtil.js"
pin "diagram-js/lib/util/RenderUtil", to: "https://ga.jspm.io/npm:diagram-js@14.11.3/lib/util/RenderUtil.js"
pin "diagram-js/lib/util/SvgTransformUtil", to: "https://ga.jspm.io/npm:diagram-js@14.11.3/lib/util/SvgTransformUtil.js"
pin "diagram-js/lib/util/Text", to: "https://ga.jspm.io/npm:diagram-js@14.11.3/lib/util/Text.js"
pin "didi", to: "https://ga.jspm.io/npm:didi@10.2.2/dist/index.js"
pin "ids", to: "https://ga.jspm.io/npm:ids@1.0.5/dist/index.esm.js"
pin "inherits-browser", to: "https://ga.jspm.io/npm:inherits-browser@0.1.0/dist/index.es.js"
pin "min-dash", to: "https://ga.jspm.io/npm:min-dash@4.2.2/dist/index.esm.js"
pin "min-dom", to: "https://ga.jspm.io/npm:min-dom@4.2.1/dist/index.esm.js"
pin "moddle", to: "https://ga.jspm.io/npm:moddle@6.2.3/dist/index.esm.js"
pin "moddle-xml", to: "https://ga.jspm.io/npm:moddle-xml@10.1.0/dist/index.esm.js"
pin "object-refs", to: "https://ga.jspm.io/npm:object-refs@0.4.0/dist/index.js"
pin "path-intersection", to: "https://ga.jspm.io/npm:path-intersection@3.1.0/intersect.js"
pin "saxen", to: "https://ga.jspm.io/npm:saxen@8.1.2/dist/index.js"
pin "tiny-svg", to: "https://ga.jspm.io/npm:tiny-svg@3.1.3/dist/index.esm.js"
